### ISSUE TITLE
Question about notifications

### ISSUE THREAD

**Issue by ahumblet** [raralabs/pm5-emulator#15]
From what I understand, when a client enables notifications on a characteristic, the PM5 will periodically emit that characteristic until the client disables notifications on that characteristic. I saw that notification handlers are not implemented by default on most characteristics of your emulator. I was able to modify rowing.go so that a single characteristic value is returned when notifications are enabled, but I did not find any code that would cause values to be periodically emitted indefinitely. Is this correct? If so, is this a feature you plan on adding? 

Thanks for your help!

**Comment by anisbhsl** [comment]
@ahumblet 

>From what I understand, when a client enables notifications on a characteristic, the PM5 will periodically emit that characteristic until the client disables notifications on that characteristic. I saw that notification handlers are not implemented by default on most characteristics of your emulator. 

Part of what we did for emulating purpose required notification handlers on certain characteristics. However, client can enable notifications on multiple characteristics and PM5 can periodically publish information on those. 


>I was able to modify rowing.go so that a single characteristic value is returned when notifications are enabled, but I did not find any code that would cause values to be periodically emitted indefinitely. Is this correct?

Yes. This was done in purpose so that users could write their own handlers. You can create a custom service and implement receiver functions and wrap the notify handler function with your receiver function like this:

```
type MyWorkout struct{

} 


func (mw *MyWorkout) notifyHandler() func(r gatt.Request, n gatt.Notifier) {
      //your logic here 
      return func(r gatt.Request, n gatt.Notifier) {
           //publish data here 
      }
}
````

and on ```rowing.go``` you can add this handler by creating an instance of ```MyWorkout``` as something like this: 

```
 multiplexedInfoChar.HandleNotifyFunc(myWorkout.notifyHandler)
```

*this is only a general idea of how you can implement your own service^^^*

> If so, is this a feature you plan on adding?

We had discussed this before (thought of exposing an interface allowing users to register their services) but **there is no plan on adding this as of now**. However, if you like you can always submit a PR. :) 

Hope this helped.

**Comment by MoralCode** [comment]
basic notification sending capabilities for single characteristics (not the multiplex one) have been added as of #17
